# Load all Season Standings from HTML

In [5]:
from pathlib import Path

import pandas as pd
import polars as pl

PATH_TO_DATA: Path = Path("./data/premier-league")
SEASONS: tuple[str] = (
    "2024-2025",
    "2023-2024",
    "2022-2023",
    "2021-2022",
    "2020-2021",
    "2019-2020",
    "2018-2019",
    "2017-2018",
    "2016-2017",
    "2015-2016",
    "2014-2015",
    "2013-2014",
    "2012-2013",
    "2011-2012",
    "2010-2011",
    "2009-2010",
    "2008-2009",
    "2007-2008",
    "2006-2007",
    "2005-2006",
    "2004-2005",
    "2003-2004",
    "2002-2003",
    "2001-2002",
    "2000-2001",
    "1999-2000",
    "1998-1999",
    "1997-1998",
    "1996-1997",
    "1995-1996",
    "1994-1995",
    "1993-1994",
    "1992-1993",
)

In [6]:
all_seasons: list[pl.DataFrame] = [None] * len(SEASONS)

for i, s in enumerate(SEASONS):
    data = pd.read_html(
        io=PATH_TO_DATA / f"standings_{s}.html",
        flavor="lxml",
        dtype_backend="pyarrow",
        encoding="utf-8",
    )[0]
    data["s"] = s
    _df: pd.DataFrame = data[
        ["s", "Rk", "Squad", "MP", "W", "D", "L", "GF", "GA", "Pts"]
    ]
    all_seasons[i] = pl.from_pandas(_df).select(
        pl.col("s").alias("season"),
        pl.col("Rk").cast(pl.Int8).alias("position"),
        pl.col("Squad").alias("squad"),
        pl.col("MP").cast(pl.Int8).alias("matches_played"),
        pl.col("W").cast(pl.Int8).alias("wins"),
        pl.col("D").cast(pl.Int8).alias("draws"),
        pl.col("L").cast(pl.Int8).alias("losses"),
        pl.col("GF").cast(pl.Int8).alias("goals_for"),
        pl.col("GA").cast(pl.Int8).alias("goals_against"),
        pl.col("Pts").cast(pl.Int8).alias("points"),
    )

df: pl.DataFrame = pl.concat(all_seasons)
del all_seasons, _df, data

In [45]:
df.head()

shape: (5, 10)
┌───────────┬──────────┬─────────────┬─────────────┬───┬────────┬───────────┬─────────────┬────────┐
│ season    ┆ position ┆ squad       ┆ matches_pla ┆ … ┆ losses ┆ goals_for ┆ goals_again ┆ points │
│ ---       ┆ ---      ┆ ---         ┆ yed         ┆   ┆ ---    ┆ ---       ┆ st          ┆ ---    │
│ str       ┆ i8       ┆ str         ┆ ---         ┆   ┆ i8     ┆ i8        ┆ ---         ┆ i8     │
│           ┆          ┆             ┆ i8          ┆   ┆        ┆           ┆ i8          ┆        │
╞═══════════╪══════════╪═════════════╪═════════════╪═══╪════════╪═══════════╪═════════════╪════════╡
│ 2024-2025 ┆ 1        ┆ Liverpool   ┆ 38          ┆ … ┆ 4      ┆ 86        ┆ 41          ┆ 84     │
│ 2024-2025 ┆ 2        ┆ Arsenal     ┆ 38          ┆ … ┆ 4      ┆ 69        ┆ 34          ┆ 74     │
│ 2024-2025 ┆ 3        ┆ Manchester  ┆ 38          ┆ … ┆ 9      ┆ 72        ┆ 44          ┆ 71     │
│           ┆          ┆ City        ┆             ┆   ┆        ┆           ┆             ┆        │
│ 2024-2025 ┆ 4        ┆ Chelsea     ┆ 38          ┆ … ┆ 9      ┆ 64        ┆ 43          ┆ 69     │
│ 2024-2025 ┆ 5        ┆ Newcastle   ┆ 38          ┆ … ┆ 12     ┆ 68        ┆ 47          ┆ 66     │
│           ┆          ┆ Utd         ┆             ┆   ┆        ┆           ┆             ┆        │
└───────────┴──────────┴─────────────┴─────────────┴───┴────────┴───────────┴─────────────┴────────┘

In [18]:
df.write_csv(
    Path("standings.csv"),
    include_bom=True,
    include_header=True,
    separator=","
)

In [19]:
THIRTY_SEVEN_COLUMN_INDEX: tuple[tuple[str, str], ...] = (
    ("Demographics", "Rk"),
    ("Demographics", "Player"),
    ("Demographics", "Nation"),
    ("Demographics", "Pos"),
    ("Demographics", "Squad"),
    ("Demographics", "Age"),
    ("Demographics", "Born"),
    ("Playing Time", "MP"),
    ("Playing Time", "Starts"),
    ("Playing Time", "Min"),
    ("Playing Time", "90s"),
    ("Performance", "Gls"),
    ("Performance", "Ast"),
    ("Performance", "G+A"),
    ("Performance", "G-PK"),
    ("Performance", "PK"),
    ("Performance", "PKatt"),
    ("Performance", "CrdY"),
    ("Performance", "CrdR"),
    ("Expected", "xG"),
    ("Expected", "npxG"),
    ("Expected", "xAG"),
    ("Expected", "npxG+xAG"),
    ("Progression", "PrgC"),
    ("Progression", "PrgP"),
    ("Progression", "PrgR"),
    ("Per 90 Minutes", "Gls"),
    ("Per 90 Minutes", "Ast"),
    ("Per 90 Minutes", "G+A"),
    ("Per 90 Minutes", "G-PK"),
    ("Per 90 Minutes", "G+A-PK"),
    ("Per 90 Minutes", "xG"),
    ("Per 90 Minutes", "xAG"),
    ("Per 90 Minutes", "xG+xAG"),
    ("Per 90 Minutes", "npxG"),
    ("Per 90 Minutes", "npxG+xAG"),
    ("Matches", "hyperlink"),
)

TWENTY_FIVE_COLUMN_INDEX: tuple[tuple[str, str], ...] = (
    ("Demographics", "Rk"),
    ("Demographics", "Player"),
    ("Demographics", "Nation"),
    ("Demographics", "Pos"),
    ("Demographics", "Squad"),
    ("Demographics", "Age"),
    ("Demographics", "Born"),
    ("Playing Time", "MP"),
    ("Playing Time", "Starts"),
    ("Playing Time", "Min"),
    ("Playing Time", "90s"),
    ("Performance", "Gls"),
    ("Performance", "Ast"),
    ("Performance", "G+A"),
    ("Performance", "G-PK"),
    ("Performance", "PK"),
    ("Performance", "PKatt"),
    ("Performance", "CrdY"),
    ("Performance", "CrdR"),
    ("Per 90 Minutes", "Gls"),
    ("Per 90 Minutes", "Ast"),
    ("Per 90 Minutes", "G+A"),
    ("Per 90 Minutes", "G-PK"),
    ("Per 90 Minutes", "G+A-PK"),
    ("Matches", "hyperlink"),
)

CHAMPIONS = {
    "2024-2025": "Liverpool",
    "2023-2024": "Manchester City",
    "2022-2023": "Manchester City",
    "2021-2022": "Manchester City",
    "2020-2021": "Manchester City",
    "2019-2020": "Liverpool",
    "2018-2019": "Manchester City",
    "2017-2018": "Manchester City",
    "2016-2017": "Chelsea",
    "2015-2016": "Leicester City",
    "2014-2015": "Chelsea",
    "2013-2014": "Manchester City",
    "2012-2013": "Manchester Utd",
    "2011-2012": "Manchester City",
    "2010-2011": "Manchester Utd",
    "2009-2010": "Chelsea",
    "2008-2009": "Manchester Utd",
    "2007-2008": "Manchester Utd",
    "2006-2007": "Manchester Utd",
    "2005-2006": "Chelsea",
    "2004-2005": "Chelsea",
    "2003-2004": "Arsenal",
    "2002-2003": "Manchester Utd",
    "2001-2002": "Arsenal",
    "2000-2001": "Manchester Utd",
    "1999-2000": "Manchester Utd",
    "1998-1999": "Manchester Utd",
    "1997-1998": "Arsenal",
    "1996-1997": "Manchester Utd",
    "1995-1996": "Manchester Utd",
    "1994-1995": "Blackburn",
    "1993-1994": "Manchester Utd",
    "1992-1993": "Manchester Utd",
}


def html_to_flat_dataframe(path_to_html: Path) -> pd.DataFrame:
    """Bring in a column-MultiIndex from HTML and make it single-level."""
    html_read = pd.read_html(
        path_to_html, flavor="lxml", dtype_backend="pyarrow", encoding="utf-8",
    )
    df: pd.DataFrame = html_read[0]
    if df.shape[1] == 37:
        df.columns = THIRTY_SEVEN_COLUMN_INDEX
    elif df.shape[1] == 25:
        df.columns = TWENTY_FIVE_COLUMN_INDEX
    else:
        _msg: str = (
            f"Unexpected number of columns, {len(df)}, "
            f"from file '{path_to_html.resolve()}'."
        )
        raise RuntimeError(_msg)

    desired_columns: list[str, str, str, str, str, str] = [
        "Squad",
        "Player",
        "Age",
        "Min",
        "Gls",
        "Ast",
    ]
    # If Age, Gls, or Ast value is a non-number string,
    # it's an HTML parsing artifact and is to be dropped
    if df.shape[1] == 25:
        subset: pd.DataFrame = df.loc[
            (df.loc[:, ("Demographics", "Age")].str.isnumeric())
            & (df[("Performance", "Gls")].str.isnumeric())
            & (df[("Performance", "Ast")].str.isnumeric()),
            pd.IndexSlice[
                ("Demographics", "Playing Time", "Performance"),
                desired_columns,
            ],
        ].copy()
    else:
        subset: pd.DataFrame = df.loc[
            :,
            pd.IndexSlice[
                ("Demographics", "Playing Time", "Performance"),
                desired_columns,
            ],
        ].copy()
    subset.columns = subset.columns.droplevel(0)
    subset["Age"] = subset["Age"].astype("int16[pyarrow]")
    subset["Min"] = subset["Min"].astype("int16[pyarrow]")
    subset["Gls"] = subset["Gls"].astype("int16[pyarrow]")
    subset["Ast"] = subset["Ast"].astype("int16[pyarrow]")

    return subset

In [46]:
all_scorers: list[pl.DataFrame] = [None] * len(CHAMPIONS)

for i, (szn, champ) in enumerate(CHAMPIONS.items()):
    _scoring: pl.DataFrame = pl.from_pandas(
        html_to_flat_dataframe(Path(f"data/premier-league/fbref_{szn}.html")),
    )
    all_scorers[i] = _scoring.with_columns(
        pl.lit(szn).alias("season"),
        pl.lit(champ).alias("champion"),
    )
data: pl.DataFrame = pl.concat(all_scorers)

In [47]:
data

shape: (18_100, 8)
┌────────────────┬───────────────────┬─────┬──────┬─────┬─────┬───────────┬────────────────┐
│ Squad          ┆ Player            ┆ Age ┆ Min  ┆ Gls ┆ Ast ┆ season    ┆ champion       │
│ ---            ┆ ---               ┆ --- ┆ ---  ┆ --- ┆ --- ┆ ---       ┆ ---            │
│ str            ┆ str               ┆ i16 ┆ i16  ┆ i16 ┆ i16 ┆ str       ┆ str            │
╞════════════════╪═══════════════════╪═════╪══════╪═════╪═════╪═══════════╪════════════════╡
│ Bournemouth    ┆ Max Aarons        ┆ 24  ┆ 86   ┆ 0   ┆ 0   ┆ 2024-2025 ┆ Liverpool      │
│ Chelsea        ┆ Joshua Acheampong ┆ 18  ┆ 170  ┆ 0   ┆ 0   ┆ 2024-2025 ┆ Liverpool      │
│ Bournemouth    ┆ Tyler Adams       ┆ 25  ┆ 1965 ┆ 0   ┆ 3   ┆ 2024-2025 ┆ Liverpool      │
│ Chelsea        ┆ Tosin Adarabioyo  ┆ 26  ┆ 1409 ┆ 1   ┆ 1   ┆ 2024-2025 ┆ Liverpool      │
│ Brighton       ┆ Simon Adingra     ┆ 22  ┆ 1097 ┆ 2   ┆ 2   ┆ 2024-2025 ┆ Liverpool      │
│ …              ┆ …                 ┆ …   ┆ …    ┆ …   ┆ …   ┆ …         ┆ …              │
│ Middlesbrough  ┆ Tommy Wright      ┆ 26  ┆ 3044 ┆ 5   ┆ 8   ┆ 1992-1993 ┆ Manchester Utd │
│ Ipswich Town   ┆ Frank Yallop      ┆ 28  ┆ 452  ┆ 2   ┆ 0   ┆ 1992-1993 ┆ Manchester Utd │
│ Aston Villa    ┆ Dwight Yorke      ┆ 20  ┆ 1918 ┆ 6   ┆ 3   ┆ 1992-1993 ┆ Manchester Utd │
│ Ipswich Town   ┆ Eddie Youds       ┆ 22  ┆ 1012 ┆ 0   ┆ 0   ┆ 1992-1993 ┆ Manchester Utd │
│ Crystal Palace ┆ Eric Young        ┆ 32  ┆ 3085 ┆ 6   ┆ 0   ┆ 1992-1993 ┆ Manchester Utd │
└────────────────┴───────────────────┴─────┴──────┴─────┴─────┴───────────┴────────────────┘

In [63]:
df.join(
    data,
    how="full",
    left_on=["season", "squad"],
    right_on=["season", "Squad"],
    validate="1:m",
).drop(["season_right", "Squad"]).select(
    pl.col("season"),
    pl.col("champion"),
    pl.col("squad"),
    pl.col("position").alias("standing"),
    pl.col("matches_played"),
    pl.col("points"),
    pl.col("wins"),
    pl.col("draws"),
    pl.col("losses"),
    pl.col("goals_for"),
    pl.col("goals_against"),
    pl.col("Player").alias("footballer"),
    pl.col("Min").alias("minutes_played"),
    pl.col("Gls").alias("goals"),
    pl.col("Ast").alias("assists"),
).sort(
    pl.col("season"), pl.col("standing"), pl.col("goals"), descending=(True, False, True),
).write_csv(
    Path("premier-league-data.tsv"),
    include_bom=True,
    include_header=True,
    separator="\t",
)

In [74]:
alldata = df.join(
    data,
    how="full",
    left_on=["season", "squad"],
    right_on=["season", "Squad"],
    validate="1:m",
).drop(["season_right", "Squad"]).select(
    pl.col("season"),
    pl.col("champion"),
    pl.col("squad"),
    pl.col("position").alias("standing"),
    pl.col("matches_played"),
    pl.col("points"),
    pl.col("wins"),
    pl.col("draws"),
    pl.col("losses"),
    pl.col("goals_for"),
    pl.col("goals_against"),
    pl.col("Player").alias("footballer"),
    pl.col("Min").alias("minutes_played"),
    pl.col("Gls").alias("goals"),
    pl.col("Ast").alias("assists"),
# ).sort(
#     pl.col("season"),
#     pl.col("standing"),
#     pl.col("goals"),
#     descending=(True, False, True),
).with_columns(
    # can't just use the 'goals_for' because it includes opponents' own goals!
    pl.col("goals")
    .sum()
    .over(pl.col("season"), pl.col("squad"))
    .alias("squad_goals_no_own"),
    pl.col("goals")
    .truediv(pl.col("goals").sum().over(pl.col("season"), pl.col("squad")))
    .alias("prop_squad_goals_no_own")
    .cast(pl.Float32),
).sort(
    pl.col("prop_squad_goals_no_own"), descending=True
)

In [95]:
alldata.with_columns(
    pl.col("prop_squad_goals_no_own").max().over(pl.col("season"), pl.col("squad")).alias("max_prop"),
).filter(
    pl.col("prop_squad_goals_no_own") == pl.col("max_prop"),
).drop(
    pl.col("max_prop")
).shape

(753, 17)

In [94]:
alldata.with_columns(
    pl.col("prop_squad_goals_no_own").max().over(pl.col("season"), pl.col("squad")).alias("max_prop"),
).filter(
    pl.col("prop_squad_goals_no_own") == pl.col("max_prop"),
).drop(
    pl.col("max_prop")
).head(n=20)

shape: (20, 17)
┌───────────┬─────────────┬─────────────┬──────────┬───┬───────┬─────────┬────────────┬────────────┐
│ season    ┆ champion    ┆ squad       ┆ standing ┆ … ┆ goals ┆ assists ┆ squad_goal ┆ prop_squad │
│ ---       ┆ ---         ┆ ---         ┆ ---      ┆   ┆ ---   ┆ ---     ┆ s_no_own   ┆ _goals_no_ │
│ str       ┆ str         ┆ str         ┆ i8       ┆   ┆ i16   ┆ i16     ┆ ---        ┆ own        │
│           ┆             ┆             ┆          ┆   ┆       ┆         ┆ i64        ┆ ---        │
│           ┆             ┆             ┆          ┆   ┆       ┆         ┆            ┆ f32        │
╞═══════════╪═════════════╪═════════════╪══════════╪═══╪═══════╪═════════╪════════════╪════════════╡
│ 2002-2003 ┆ Manchester  ┆ Southampton ┆ 8        ┆ … ┆ 23    ┆ 2       ┆ 42         ┆ 0.547619   │
│           ┆ Utd         ┆             ┆          ┆   ┆       ┆         ┆            ┆            │
│ 2016-2017 ┆ Chelsea     ┆ Sunderland  ┆ 20       ┆ … ┆ 15    ┆ 2       ┆ 28         ┆ 0.535714   │
│ 2009-2010 ┆ Chelsea     ┆ Sunderland  ┆ 13       ┆ … ┆ 24    ┆ 1       ┆ 45         ┆ 0.533333   │
│ 1999-2000 ┆ Manchester  ┆ Sunderland  ┆ 7        ┆ … ┆ 30    ┆ 4       ┆ 57         ┆ 0.526316   │
│           ┆ Utd         ┆             ┆          ┆   ┆       ┆         ┆            ┆            │
│ 2021-2022 ┆ Manchester  ┆ Norwich     ┆ 20       ┆ … ┆ 11    ┆ 3       ┆ 21         ┆ 0.52381    │
│           ┆ City        ┆ City        ┆          ┆   ┆       ┆         ┆            ┆            │
│ …         ┆ …           ┆ …           ┆ …        ┆ … ┆ …     ┆ …       ┆ …          ┆ …          │
│ 2003-2004 ┆ Arsenal     ┆ Arsenal     ┆ 1        ┆ … ┆ 30    ┆ 6       ┆ 69         ┆ 0.434783   │
│ 2019-2020 ┆ Liverpool   ┆ Southampton ┆ 11       ┆ … ┆ 22    ┆ 2       ┆ 51         ┆ 0.431373   │
│ 2003-2004 ┆ Arsenal     ┆ Newcastle   ┆ 5        ┆ … ┆ 22    ┆ 4       ┆ 51         ┆ 0.431373   │
│           ┆             ┆ Utd         ┆          ┆   ┆       ┆         ┆            ┆            │
│ 2016-2017 ┆ Chelsea     ┆ Everton     ┆ 7        ┆ … ┆ 25    ┆ 6       ┆ 58         ┆ 0.431034   │
│ 2017-2018 ┆ Manchester  ┆ Tottenham   ┆ 3        ┆ … ┆ 30    ┆ 2       ┆ 70         ┆ 0.428571   │
│           ┆ City        ┆             ┆          ┆   ┆       ┆         ┆            ┆            │
└───────────┴─────────────┴─────────────┴──────────┴───┴───────┴─────────┴────────────┴────────────┘

In [ ]:
alldata.with_columns(
    pl.col("prop_squad_goals_no_own")
    .max()
    .over(pl.col("season"), pl.col("squad"))
    .alias("max_prop"),
).filter(pl.col("prop_squad_goals_no_own") == pl.col("max_prop")).select(
    pl.col("season"),
    pl.col("squad"),
    pl.col("standing"),
    pl.col("points"),
    pl.col("prop_squad_goals_no_own"),
).select(
    pl.corr("prop_squad_goals_no_own", "standing").alias(
        "goals_proportion_corr_with_standing"
    ),
    pl.corr("prop_squad_goals_no_own", "points").alias(
        "goals_proportion_corr_with_points"
    ),
)

shape: (1, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ goals_proportion_corr_with_sta… ┆ goals_proportion_corr_with_poi… │
│ ---                             ┆ ---                             │
│ f32                             ┆ f32                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ -0.139374                       ┆ 0.141656                        │
└─────────────────────────────────┴─────────────────────────────────┘

In [81]:
alldata.select(pl.corr("prop_squad_goals_no_own", "points"))

shape: (1, 1)
┌─────────────────────────┐
│ prop_squad_goals_no_own │
│ ---                     │
│ f32                     │
╞═════════════════════════╡
│ 0.025546                │
└─────────────────────────┘